--테이블 생성
  CREATE TABLE "PC01"."TB_JDBC_BOARD" 
   (	"BOARD_NO" NUMBER(3,0), 
	"TITLE" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(20 BYTE), 
	"USER_ID" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE
   );
   
   
--조회
SELECT *
FROM TB_JDBC_BOARD;


--테이블 컬럼내용 삭제
DELETE FROM TB_JDBC_BOARD;
COMMIT;

INSERT INTO TB_JDBC_BOARD VALUES(1,1,1,1,SYSDATE);

--테이블명 수정
ALTER TABLE TB_JDBC_BOARD RENAME COLUMN TILTE to TITLE;

commit;