--생성
  CREATE TABLE "PC01"."TB_JDBC_USER" 
   ("USER_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "TB_JDBC_USER_PK" PRIMARY KEY ("USER_ID")
     );
    
--삭제
DROP TABLE TB_JDBC_USER;
COMMIT;

--조회
SELECT * 
FROM TB_JDBC_USER;